// User Activity Tracking for Limits (Auto-generated by Windsurf)
const userActivityTracker = {
    getActivityData() {
        const key = `activity_${userData.id}`;
        const data = localStorage.getItem(key);
        return data ? JSON.parse(data) : {
            quiz: { count: 0, lastReset: Date.now() },
            scratch: { count: 0, lastReset: Date.now() },
            ad: { count: 0, lastReset: Date.now() }
        };
    },
    saveActivityData(data) {
        localStorage.setItem(`activity_${userData.id}`, JSON.stringify(data));
    },
    checkLimit(type, limit, recoveryHours) {
        const data = this.getActivityData();
        const activity = data[type];
        const now = Date.now();
        const recoveryMs = recoveryHours * 60 * 60 * 1000;
        if (now - activity.lastReset >= recoveryMs) {
            activity.count = 0;
            activity.lastReset = now;
            this.saveActivityData(data);
            return { allowed: true, remaining: limit };
        }
        if (activity.count >= limit) {
            const timeUntilReset = activity.lastReset + recoveryMs - now;
            const hoursRemaining = Math.ceil(timeUntilReset / (60 * 60 * 1000));
            return { allowed: false, remaining: 0, hoursRemaining };
        }
        return { allowed: true, remaining: limit - activity.count };
    },
    increment(type) {
        const data = this.getActivityData();
        if (data[type]) { data[type].count++; this.saveActivityData(data); }
    }
};

// Ad Cooldown System (Auto-generated by Windsurf)
const adCooldownTracker = {
    getLastAdTime() {
        const key = `lastAd_${userData.id}`;
        const time = localStorage.getItem(key);
        return time ? parseInt(time) : 0;
    },
    setLastAdTime() {
        localStorage.setItem(`lastAd_${userData.id}`, Date.now().toString());
    },
    checkCooldown() {
        const cooldownSeconds = window.appCostConfig?.adCooldownSeconds || 5;
        const lastTime = this.getLastAdTime();
        const now = Date.now();
        const cooldownMs = cooldownSeconds * 1000;
        const timeSinceLast = now - lastTime;

        if (timeSinceLast < cooldownMs) {
            const remainingMs = cooldownMs - timeSinceLast;
            const remainingSeconds = Math.ceil(remainingMs / 1000);
            return { allowed: false, remainingSeconds, remainingMs };
        }
        return { allowed: true, remainingSeconds: 0 };
    },
    showCooldownToast(remainingSeconds) {
        window.showToast(`⏳ Please wait ${remainingSeconds}s before next ad`, 'warning');
    }
};

// Check ad cooldown before running ad-based action
function checkAdCooldown() {
    const check = adCooldownTracker.checkCooldown();
    if (!check.allowed) {
        adCooldownTracker.showCooldownToast(check.remainingSeconds);
        if (tg.HapticFeedback) tg.HapticFeedback.notificationOccurred('error');
        return false;
    }
    return true;
}

function checkActivityLimit(type, limit, hours, name) {
    const check = userActivityTracker.checkLimit(type, limit, hours);
    if (!check.allowed) {
        window.showToast(`⏳ ${name} limit reached! Try again in ${check.hoursRemaining}h`, 'warning');
        if (tg.HapticFeedback) tg.HapticFeedback.notificationOccurred('error');
        return false;
    }
    return true;
}
